apiVersion: apps/v1
kind: Deployment
metadata:
  name: mspr-cart-api-deployment
  namespace: prod-mspr-ci
spec:
  selector:
    matchLabels:
      app: mspr-cart-api
  replicas: 1
  template:
    metadata:
      labels:
        app: mspr-cart-api
    spec:
      containers:
      - name: mspr-cart-api
        image: "docker.pkg.github.com/shyndard/mspr-cart-api/api:latest"
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: $DATABASE_URL
        - name: DB_USERNAME
          value: $DB_USERNAME
        - name: DB_PASSWORD
          value: $DB_PASSWORD
      imagePullSecrets:
      - name: regcredmael
        