kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: maven:3.3.3-jdk-8-onbuild
    commands:
      - mvn clean install
  - name: Semantical Versionning
    image: python:3.6
    commands:
      - mkdir ~/.ssh
      - echo $CI_SSH_KEY > ~/.ssh/id_rsa
      - pip install -r .semver/requirements.txt
      - python .semver/main.py
    environment:
      CI_REPOSITORY_URL:
        from_secret: CI_REPOSITORY_URL
      CI_SSH_KEY:
        from_secret: CI_SSH_KEY
    depends_on: [build]
    when:
      branch:
      - master
      event: push
