kind: pipeline
type: kubernetes
name: default

steps:
  - name: install_dependencies
    image: maven:3.6.3-jdk-8
    commands:
      - mvn dependency:purge-local-repository
    volumes:
      - name: cache
        path: /root/.m2/
  - name: test
    image: maven:3.6.3-jdk-8
    commands:
      - mvn test -o
    volumes:
      - name: cache
        path: /root/.m2/
    depends_on: [install_dependencies]
  - name: build
    image: maven:3.6.3-jdk-8
    commands:
      - mvn clean install -DskipTests=true -o
    volumes:
      - name: cache
        path: /root/.m2/
    depends_on: [install_dependencies]
  - name: create_docker
    image: banzaicloud/drone-kaniko
    settings:
      email: $GITHUB_EMAIL
      dockerfile: ./Dockerfile.jvm
      registry: docker.pkg.github.com
      repo: shyndard/mspr-cart-api/api
      username:
        from_secret: github_username
      password:
        from_secret: github_token
    environment:
      GITHUB_EMAIL:
        from_secret: GITHUB_EMAIL
    depends_on: [build, test]
    when:
      branch: master
volumes:
  - name: cache
    temp: {}
