kind: pipeline
type: kubernetes
name: default

services:
  - name: postgres
    image: postgres:latest
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

steps:
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
  - name: test
    image: maven:3.6.3-jdk-8
    commands:
      - mvn test
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on: [postgres]
  - name: build
    image: maven:3.6.3-jdk-8
    commands:
      - mvn clean install -DskipTests=true
  - name: create_docker
    image: banzaicloud/drone-kaniko
    settings:
      email: $GITHUB_EMAIL
      dockerfile: ./Dockerfile.jvm
      registry: docker.pkg.github.com
      repo: shyndard/mspr-cart-api/api
      username:
        from_secret: github_username
      password:
        from_secret: github_token
    environment:
      GITHUB_EMAIL:
        from_secret: GITHUB_EMAIL
    depends_on: [build, test, code-analysis]
    when:
      event: tag
  - name: rollout
    image: pabloclsn/kubectl-docker:latest
    commands:
      - echo $KUBE_CONFIG > ~/.kube/config
      - cat .kube/deployment.yaml | envsubst | kubectl apply -f -
      - kubectl rollout restart deployment/mspr-cart-api-deployment -n prod-mspr-ci
    environment:
      DB_URL:
        from_secret: DB_URL
      DB_USERNAME:
        from_secret: DB_USERNAME
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
    depends_on: [create_docker]
    #when:
      #event: tag
